# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2012934bb3b517ed5910ac35c5ad480c48a936a4ada34ff3f4d4b7e8cb3a809ecdc1b89196bdb020e00d2a7ab1aefb214652260192225be41057133ab2d1c47

test:
  secret_key_base: dbd9c5ed5be6ac0bb707524ca69584497e8d59ea73a2ee92715652c781d418a7bc69071b74966c1b643dda4d4fe24c369ecd1d396fea11d43c9b9379d9110935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
